name: docker.yml
on:
  # Manual trigger
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Set image name
        run: |
          echo "IMAGE_NAME=ghcr.io/${{ github.repository }}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Download required file
        run: chmod +x ./scripts/download-jar.sh && ./scripts/download-jar.sh

      - name: Build Image
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          push: false
          tags: |
            ${{ env.IMAGE_NAME }}:test
            ${{ env.IMAGE_NAME }}:latest

      - name: Test
        run: chmod +x ./scripts/test.sh && ./scripts/test.sh ${{ env.IMAGE_NAME }}:test

      - name: Push Image
        run: docker push ${{ env.IMAGE_NAME }}:latest
